getsentry/rust-sourcemap

- examples/read.rs
This PR adds the usage example from https://github.com/mitsuhiko/rust-sourcemap/blob/fa7065ab3529c646979ab0c39d3d655dd943cd8c/src/lib.rs#L26-L39 as a runnable example binary (`cargo run --example read <path> [line=0] [column=0]`)
> Add "read" example from API documentation

- src/decoder.rs
This diff shaves around 5% off sourcemapping large files by eagerly skipping empty lines.
> Skip empty sections of the VLQ

- src/decoder.rs
- src/encoder.rs
- src/jsontypes.rs
- tests/test_decoder.rs
This regression likely occurred with the move from serde 0.9 to 1.0. I suppose that it used to consider defaultable values optional and coerce null into default.
Anyway, I didn't want to change too much, so the only thing that has changed is that sources are now optional. This was actually uncovered by a test in sentry, which is now ported over to this repo.
> fix: Regression when source files are null

- src/sourceview.rs
Changed in Rust 1.35.
https://github.com/rust-lang/rust-clippy/blob/ba6681300e9d7a10379c9fbbf539f4f3261fdc6a/CHANGELOG.md#rust-135
> fix: Rename cyclomatic_complexity to cognitive_complexity.

- src/builder.rs
- src/types.rs
Guard APIs that depend on `Url::to_file_path` and `Url::from_directory_path` on the same platforms as rust-url.
This allows to compile rust-sourcemap on other platforms (e.g. `wasm32-unknown-unknown`) without errors.
> Propagate cfg guards from rust-url

- src/builder.rs
add_raw is very important for performance as SourceMapBuilder.add_source copies the whole source code.
I created a new pr to make commit log cleaner
> Add SourceMapBuilder.add_raw

- src/detector.rs
- src/hermes.rs
- src/jsontypes.rs
- src/sourceview.rs
- src/types.rs
- tests/test_detector.rs
This is a backwards incompatible change to the crate which adds some missing API and changes how sourcemap references work.
I ran across this trying to use this crate for building a source map debug tool.
> feat: Minimal API changes to source map references

- src/detector.rs
This change adds back support for targeting `wasm32-unknown-unknown`. 
```
error[E0599]: no function or associated item named `from_file_path` found for struct `url::Url` in the current scope
--> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sourcemap-6.0.0/src/detector.rs:54:32
|
54 |         resolve_url(url, &Url::from_file_path(&minified_path).ok()?)
|                                ^^^^^^^^^^^^^^ function or associated item not found in `url::Url`
error[E0599]: no method named `to_file_path` found for struct `url::Url` in the current scope
--> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sourcemap-6.0.0/src/detector.rs:55:29
|
55 |             .and_then(|x| x.to_file_path().ok())
|                             ^^^^^^^^^^^^ method not found in `url::Url` …
```
> Conditionally compile SourceMapRef.resolve_path based on target support

- src/types.rs
This will help reduce ambiguity a bit.
> doc: add documentation saying lines and columns are 0-indexed

- src/builder.rs
- src/decoder.rs
- src/encoder.rs
- src/types.rs
- tests/test_builder.rs
Fixes https://github.com/getsentry/rust-sourcemap/issues/50
> feat: Add source_root handling support

- examples/rewrite.rs
- src/detector.rs
- src/hermes.rs
- src/types.rs
- src/utils.rs
- tests/test_index.rs
- tests/test_regular.rs
With suggestions applied and clippy fixed again
https://github.com/getsentry/rust-sourcemap/pull/53
> Jridgewell index

- Cargo.toml
- src/js_identifiers.rs
- src/lib.rs
- src/ram_bundle.rs
- src/sourceview.rs
- src/utils.rs
My motivations here are to learn about, and ideally improve the performance of, rust-based frontend tooling.
The regex crate is used in two separate parts of this lib, **in both cases I have ended up making behavioural changes** - *which I can undo to be more compatible if desired*.
* `filename: &str` -> `index: usize` parsing  in code managing compressed source bundles
* No longer are any files in the bundle directory ignored, they must all be understood and used by the bundler.
* I explored a few different options here: https://github.com/willstott101/rust-sourcemap/commit/c6d1debe0df4096c0882859e5b6fa6c9daac693d
* Finding and introspecting JavaScript identifiers
* `is_valid_javascript_identifier` no longer returns true for invalid identifiers with valid prefixes (see commented test …
> Remove regex dependency for faster runtime, and compile

- Cargo.toml
- src/decoder.rs
This switches out the `base64` create for `data-encoding` which is nicer to use.
Refs https://github.com/marshallpierce/rust-base64/issues/213 and https://github.com/marshallpierce/rust-base64/issues/205
> feat: Switch base64 create for data-encoding

- src/utils.rs
When we switched to Rust's `binary_search_by_key`, we accidentally changed the behavior when a token matches exactly. Before, we were guaranteed to always return the lowest index because we didn't stop iterating when we found a match. Now, we exit as soon as we find a match, which can be any matching based on the size of the slice.
Fixes https://github.com/swc-project/swc/pull/6973
> Ensure greatest_lower_bound returns lowest match index

- src/decoder.rs
- tests/test_decoder.rs
This makes some configurations of Webpack, which emit `"sourceRoot": "webpack:///"` work as expected, and allowing CLI to rewrite sources into `webpack:///./src/foo/bar.js` rather than `webpack:/./src/foo/bar.js`.
> fix: Correctly handle protocol-only sourceRoot values

- CHANGELOG.md
- Cargo.toml
- src/builder.rs
- src/decoder.rs
- src/encoder.rs
- src/jsontypes.rs
- src/types.rs
This adds support for reading and writing debug ids in sourcemaps.
Question: Do we also want `SourceMapIndex` to be able to have a debug id?
> feat: Support debug ids

- src/types.rs
Right now it copies and overrides source over and over again 🥲
A part of bugfix for https://github.com/getsentry/sentry-cli/issues/1710 once it's updated in the cli.
> fix: Do not set source_contents if it already exists

- CHANGELOG.md
- src/types.rs
The fix turns out to be quite simple: When we look up a position in and index sourcemap, the section's column offset is only applied to its first line. Therefore we need to do the same thing when flattening.
> fix: Correctly flatten index sourcemaps

- src/decoder.rs
- src/encoder.rs
- src/types.rs
- tests/test_builder.rs
- tests/test_decoder.rs
This changes sourcemap parsing so that source names are not automatically prefixed with the `sourceRoot` field. The problem with doing that is that reading and then immediately writing a sourcemap would result in the source names changing.
Instead, `SourceMap` now maintains a copy of the vector of source names with the `sourceRoot` prefix prepended. Obviously this copy needs to be kept in sync with the original source names whenever a source name or the `sourceRoot` changes.
Note that this PR changes the behavior of `SourceMapBuilder` somewhat. Now, there is no difference between parsing a sourcemap like 
```json
{ "sourceRoot": "root", "sources": ["foo.js", "bar.js"], [...]}
```
and constructing it with a builder:
```rust
let mut builder = SourceMapBuilder::new(None); …
```
> fix: Correct sourceRoot logic

- Cargo.toml
- src/js_identifiers.rs
We've gone full circle :sweat_smile:
The `unicode-id` and `unicode-id-start` crates were cloned from [`unicode-xid`](https://crates.io/crates/unicode-xid) and [`unicode-ident`](https://crates.io/crates/unicode-ident) for usages in the [oxc project](https://github.com/oxc-project/oxc).
Oxc will be using this crate for sourcemap support, and is currently using the better optimized `unicode-id-start` crate. I don't want to include two similar dependencies due to the rather large static storage size of these crates.
The `unicode-id-start` crate is also faster and uses slightly less static storage. See full details at https://github.com/oxc-project/unicode-id-start/tree/master?tab=readme-ov-file#comparison-of-performance
---
The version "1" is used instead of the latest version because the …
> feat: Replace `unicode-id` crate with `unicode-id-start`

- Cargo.toml
- src/types.rs
- tests/test_encoder.rs
The browser identify sourcemap by two kind. It is map `json` and `data_url`, the `data_url` of sourcemap is widely used, so here add it to easy use.
> feat: add SourceMap to_data_url method

- src/sourceview.rs
Close https://github.com/getsentry/rust-sourcemap/issues/79
> refactor: make SourceView implement Sync

- src/sourceview.rs
The `*const u8` is `!Send`, here already using `Mutex` to make sure the ptr is thread-safe, so add `SourceViewLinePtr ` struct to let it implement `Send` + `Sync`.
> fix: SourceView implement Sync

- src/builder.rs
- src/decoder.rs
- src/ram_bundle.rs
- src/sourceview.rs
- src/types.rs
- tests/test_namemap.rs
Here has some unnecessary memory alloc, and the pr intends to fix them.
Here has a example.
``` rs
fn add_source_with_id(&mut self, src: &str, old_id: u32) -> u32 {
let count = self.sources.len() as u32;
let id = *self.source_map.entry(src.into()).or_insert(count); // Here `src.into` -> `String` only calculate hash, it is unnecessary.
if id == count {
self.sources.push(src.into()); // Here `src.into` -> `String` to store,  it is unnecessary.
self.sources_mapping.push(old_id);
}
id
}
```
> perf: using Arc<str> instead of String

- src/encoder.rs
- tests/test_builder.rs
- tests/test_encoder.rs
The current code generates source map like
```json
{
"mappings": ";;UAAUA;MACOC,IAAI;IACV,SAASC;QACZC,QAAQC,GAAG,GAACH;IAChB;MAFgBC,IAAAA;AAGpB,GALUF,MAAAA",
"names": [
"A",
"v",
"a",
"console",
"log"
],
"rangeMappings": ";;;;;;;;",
"sources": [
"../../input/index.ts"
],
"sourcesContent": [
"namespace A {\n    export const v = 25;\n    export function a() {\n        console.log(v);\n    }\n}\n"
],
"version": 3
}
```
where `rangeMappings` is useless. This PR modifies the encoder to skip encoding if there's no meaningful data
> feat: Skip encoding range mappings if it's empty

- Cargo.toml
The document in https://getsentry.github.io/rust-sourcemap/ seems to be too old.
How about removing the `documentation` entry from `Cargo.toml`.
If so, the latest document (https://docs.rs/sourcemap/latest/sourcemap/) will be linked from crates.io.
> Remove documentation entry from Cargo.toml

- CHANGELOG.md
- src/encoder.rs
- src/hermes.rs
- src/lib.rs
- src/sourceview.rs
- src/types.rs
- src/utils.rs
The fact that the tokens in a sourcemap can be arbitrarily ordered causes a substantial amount of complication (we have to keep a sorted index in addition) for no benefit that I've ever seen. Therefore, we now sort tokens upon creation and remove all the `Index` rigmarole. This is a breaking change because it removes some types and functions.
> ref: Sort tokens in SourceMap

- CHANGELOG.md
- src/jsontypes.rs
- src/types.rs
This partially implements #96. The debug id will still be serialized as `"debug_id"`, but can now additionally be read from `"debugId"`.
> feat: Read debug IDs from debugId field

- src/builder.rs
- src/decoder.rs
- src/encoder.rs
- src/jsontypes.rs
- src/types.rs
- tests/test_builder.rs
- tests/test_index.rs
Sourcemaps can now specify an `ignoreList`[0], a list of indexes into sources for which those sources should be shown as ignored in dev tools, for example as collapsed stack frames in program stacks.
This adds the list to the SourceMap structure but only includes it in serialized output when it’s non-zero. Open to feedback.
Added a test to exercise this through flattening indexed source maps into a regular map with updated source positions.
[0] https://tc39.es/source-map/#source-map-format
> Add support for ignoreList property

- CHANGELOG.md
- src/decoder.rs
- src/encoder.rs
- src/jsontypes.rs
- src/types.rs
Using an alias produces an error when both fields are set. The intended behavior is to only read from `"debug_id"` if `"debugId"` is not present. We now encode this logic explicitly by deserializing both and choosing manually.
> fix: Resolve conflict between "debugId" and "debug_id"

- CHANGELOG.md
- src/decoder.rs
- src/encoder.rs
- src/jsontypes.rs
- src/types.rs
#100 overzealously switched the default key from debug_id to debugId. While both should be supported, we should default to the current debug_id for now and make the switch in a considered manner.
> fix: Prefer debug_id

- .gitignore
- src/hermes.rs
- src/ram_bundle.rs
- tests/test_hermes.rs
The utility to get the original function name of a given token is slightly incorrect. 
The mappings included in the map file, for whatever reason are 1-based indexed for the lines, and 0-based for the columns.
Given that we were doing the lookup based on both 0-based indexes, sometimes the lookup was incorrect as we are pointing to line before, and in cases where the token is the very first line of the function, it may return an invalid function name (only when the column ends up being also before the `function` keyword)
I added a test case based on the testdata that we have today that points to the `throw` token of the module.js file, which is before the `function` in terms of the column, and that showed the error.
Also, here we can see that facebook uses 1-based for lines and 0-based …
> Fix Hermes get original function name

- src/decoder.rs
- src/encoder.rs
- src/js_identifiers.rs
- src/ram_bundle.rs
- src/sourceview.rs
- src/utils.rs
- src/vlq.rs
This way, tests are not compiled into binaries except when testing.
> ref(tests): Move tests under `cfg(test)`

- src/decoder.rs
- src/encoder.rs
- src/hermes.rs
- src/jsontypes.rs
- src/sourceview.rs
- src/types.rs
Also, add support for encoding and decoding the new `debug_id` field, and add tests.
In order to be able to more thoroughly test encoding/decoding, this code adds `PartialEq` and `Debug` implementations to some structs which were lacking it previously.
Closes #113
> feat: Add `debug_id` field to `SourceMapIndex`

- src/types.rs
We can move sources and source contents beforehand, assuming we will use all sources anyway.
> perf: Make `SourceMapIndex::flatten` more efficient

- src/types.rs
The size of `Range` is now 24 bytes instead of 44 bytes. `RawToken` is 28 bytes, but dereferencing it is a trivial memory move rather than an allocation.
I'll report the numbers within this week.
> perf: Make `adjust_mappings` faster by reducing the type size
